name: Abiotic Factor Build and Push Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build --no-cache --progress=plain -t ghcr.io/w4yfind3r/abiotic-factor:74416cf771fe45f3da11db19b0cabba30bbffa0b .
        docker push ghcr.io/w4yfind3r/abiotic-factor:74416cf771fe45f3da11db19b0cabba30bbffa0b
